### ISSUE TITLE
issues that happen during run with the example data(BRCA)

### ISSUE THREAD

**Issue by sunpeter2019** [abu-compbio/BetweenNet#2]
sorry to bother you again.
i came across some issues during running the code which is  generate_outliers.py .
log as follows:
################################################
    2 - Selection of Outliers...
################################################

Computing BW Differences: STARTED
Computing BW Differences: DONE03,  5.53it/s]

Computing Mean and Standard deviations: STARTED
100%|██████████| 220/220 [00:28<00:00,  7.75it/s]
  0%|          | 2/20281 [00:00<37:04,  9.12it/s]/public/home/jd_sht/local/python3/lib/python3.8/site-packages/scipy/optimize/optimize.py:761: RuntimeWarning: invalid value encountered in subtract
  np.max(np.abs(fsim[0] - fsim[1:])) <= fatol):
Traceback (most recent call last):
  File "generate_outliers.py", line 187, in <module>
    main()
  File "generate_outliers.py", line 175, in main
    genes_standard_deviation_mean=calculate_mean_std_values(bw_diff_matrix)
  File "generate_outliers.py", line 119, in calculate_mean_std_values
    truncnorm_fit=truncnorm.fit(data_specefic_gene_sorted, fix_a=0, fix_b=max(data_specefic_gene), loc=0, scale=1)
  File "/public/home/jd_sht/local/python3/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 2505, in fit
    raise Exception("Optimization converged to parameters that are "
Exception: Optimization converged to parameters that are outside the range allowed by the distribution.
  0%|          | 2/20281 [00:00<2:40:52,  2.10it/s]
------------------------------------------------------------------------------------------------------------------------------
I'd appreciate it if you could take a look at it and maybe tell me where went wrong.
 
i am looking forword to your reply and thanks for you time again.

**Comment by abu-compbio** [comment]
Hello,

I downloaded the git repo. and I run it, and it works for me, can you double-check that again?

or redownload the repo again, there might be a problem with the input data?

let me know when you try it again.

Aissa.

**Comment by sunpeter2019** [comment]
Hello, it's me again. How are you?

When i doing following operation, (g++-5 -std=c++0x -I$LEDAROOT/incl -L$LEDAROOT betweenness.cpp -lGeoW -lD3 -lW -lP -lG -lL -lX11 -lm -O1 -no-pie -o betweenness), i find that i dont have the file under $LEDAROOT. Although i have managed to download it from LEDA website, it did't work. So i wonder if you can share these file?

I would really apreciate your help and good luck with your work.

P.S: (About my last problem, it seems like the issue lies in the different package version, I retracted the package version and it works for me. Hope i can successful run your code soon.)

thanks for your reading again.

Peter.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "abu-compbio/BetweenNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月25日(星期三) 晚上11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [abu-compbio/BetweenNet] issues that happen during run with the example data(BRCA) (#2)





 
Hello,
 
I downloaded the git repo. and I run it, and it works for me, can you double-check that again?
 
or redownload the repo again, there might be a problem with the input data?
 
let me know when you try it again.
 
Aissa.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
